<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Browsershot\Browsershot;

/*
/The purpose of this controller is to generate pdf from the HTML based resume
/The html based resume is created from teh response from the AI after optimising the Resume
*/
class ResumeGenerationController extends Controller
{
    public function index()
    {
        // 1. Your HTML string
        $html = '
            <html>
              <head><style>body { font-family: sans-serif; }</style></head>
              <body>
                <h1>Hello, PDF!</h1>
                <p>This is a test generated by Browsershot.</p>
              </body>
            </html>
        ';

        // 1) Grab the real Puppeteer‐downloaded Chrome path:
        $chromePath = trim(shell_exec(<<<'CMD'
        whoami
        CMD
        ));

        // dd($chromePath);

        // dd('/root/.cache/puppeteer/chrome/linux_arm-138.0.7204.49/chrome-linux64/chrome');

        // 2. Generate the PDF binary
        $pdf = Browsershot::html($html)
            ->setNodeBinary(env('NODE_PATH'))
            // point to your NPM binary:
            ->setNpmBinary(env('NPM_PATH'))
            // point to the Chrome executable:
            ->setChromePath(env('CHROME_PATH'))
            ->format('A4')
            ->margins(10, 10, 10, 10)
            ->pdf();

        // 3. Return it as a PDF response
        return response($pdf, 200, [
            'Content-Type'        => 'application/pdf',
            'Content-Disposition' => 'inline; filename="test.pdf"',
        ]);
    }
}
